#TODO: in the CI, overwrite AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
services:
  gameloft-dynamodb:
    image: amazon/dynamodb-local
    container_name: gameloft-dynamodb
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]

  gameloft-api:
    build: "./api"
    container_name: gameloft-api
    hostname: gameloft-api
    ports:
      - "5000:5000"
    depends_on:
      - gameloft-dynamodb
    environment:
      DYNAMO_ENDPOINT: "http://gameloft-dynamodb:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local

  gameloft-dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: gameloft-dynamodb-admin
    ports:
      - "8001:8001"
    depends_on:
      - gameloft-dynamodb
    environment:
      DYNAMO_ENDPOINT: "http://gameloft-dynamodb:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
